---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  name: "ocp-adms-incident-processor"
  labels:
    app.kubernetes.io/name: "ocp-adms-incident-processor"
    app.kubernetes.io/component: "statefulset.ocp-adms-incident-processor"
spec:
  clusterIP: "None"
  externalIPs: []
  healthCheckNodePort: 0
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    app.kubernetes.io/component: "statefulset.ocp-adms-incident-processor"
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080

---
kind: "ConfigMap"
apiVersion: "v1"
data:
  app_java_opts: "-Djava.security.krb5.conf=/var/ocp/krb5.conf -Dsun.security.krb5.debug=false\
    \ -Docp.kafka.stream.cleanup.on-start=false"
  ocp_profiles_active: "dev,kafka_dev"
  ocp_config_service_uri: "http://ocp-config-svc:8080"
binaryData: {}
metadata:
  annotations: {}
  name: "ocp-adms-incident-processor"
  labels:
    app.kubernetes.io/name: "ocp-adms-incident-processor"

---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  annotations: {}
  name: "ocp-adms-incident-processor"
  labels:
    app.kubernetes.io/name: "ocp-adms-incident-processor"
    app.kubernetes.io/component: "statefulset.ocp-adms-incident-processor"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  serviceName: ""
  selector:
    matchLabels:
      app.kubernetes.io/component: "statefulset.ocp-adms-incident-processor"
    matchExpressions: []
  revisionHistoryLimit: 10
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: "ocp-adms-incident-processor"
        app.kubernetes.io/component: "statefulset.ocp-adms-incident-processor"
    spec:
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      schedulerName: "default-scheduler"
      dnsPolicy: "ClusterFirst"
      containers:
      - name: "ocp-adms-incident-processor"
        image: "nexus.duke-energy.com:18079/ocp/ocp-adms-incident-processor:1.0.0-SNAPSHOT-25"
        command: []
        args: []
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: "http"
          containerPort: 8080
          protocol: "TCP"
        env:
        - name: "APP_SERVER_IP"
          valueFrom:
            fieldRef:
              apiVersion: "v1"
              fieldPath: "status.podIP"
        - name: "APP_SERVER_NAME"
          valueFrom:
            fieldRef:
              apiVersion: "v1"
              fieldPath: "metadata.name"
        volumeMounts:
        - name: "ocp-adms-incident-processor-volume"
          readOnly: false
          mountPath: "/var/ocp/data"
        livenessProbe:
          initialDelaySeconds: 300
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 100
          httpGet:
            path: "/actuator/info"
            port: 8080
            scheme: "HTTP"
        readinessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 100
          httpGet:
            path: "/actuator/info"
            port: 8080
            scheme: "HTTP"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "2Gi"
        envFrom:
        - prefix: ""
          configMapRef:
            name: "ocp-adms-incident-processor"
            optional: false

        - prefix: ""
          secretRef:
            name: "ocp-adms-incident-processor-secrets"
            optional: false
      securityContext:
        supplementalGroups: []
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              namespaces: []
              labelSelector:
                matchLabels: {}
                matchExpressions: []
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      imagePullSecrets:
      - name: "nexus.duke-energy.com.18079"
  updateStrategy:
    type: "OnDelete"
  volumeClaimTemplates:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      annotations: {}
      name: "ocp-adms-incident-processor-volume"
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: "best-effort-m3"
      volumeMode: "Filesystem"
      resources:
        limits:
          storage: "10Gi"
        requests:
          storage: "10Gi"
